# Generated by Django 5.0.1 on 2024-01-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Тело файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='когда скачено')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
        ),
    ]
