# Generated by Django 4.2.9 on 2024-02-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files", verbose_name="Тело файла"),
        ),
    ]
